### PR TITLE
Add missing items in .h5pignore

### PR DESCRIPTION
**Pull request by otacke**

### CODE REVIEW

**Comment by rezeau** [comment]
@otacke Just found out that a few more items need to be added to .h5pignore in order to make TimeLine contents re-useable and uploaded to other sites. Here's my list of missing items:

- LICENSE
- build_info
- generate-semantics.ts
- jest.config.ts
- typings.d.ts
- public
- dist/report.html

which I've tried to add to .h5pignore
It works ok except that the only file I can't eliminate from export is dist/report.html
What am I missing?

**Comment by rezeau** [comment]
@otacke I need to explain better my issue.  This is _different_ from packing the library, which does work as expected.
When experimenting with H5P contents in my local site Drupal 7 development folder, at some stage of the development I build the H5P content and I create an instance of it on my drupal 7 local site.  With all other H5P contents that I have experimented with so far, the .h5pignore file takes care NOT to include in the library files which the upload feature will reject... But with the NDLA Timeline, whatever I try, the dist/report.html file is included in the Timeline library, and of course it makes my content instance rejected upon upload.
Because of the incomplete list of files in .h5pignore I get this long list of errors:

Validating h5p package failed.
File "H5P.NDLATimeline-0.0/LICENSE" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)
File "H5P.NDLATimeline-0.0/build_info/repos" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)
File "H5P.NDLATimeline-0.0/dist/report.html" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)
File "H5P.NDLATimeline-0.0/generate-semantics.ts" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)
File "H5P.NDLATimeline-0.0/jest.config.ts" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)
File "H5P.NDLATimeline-0.0/public/compare.html" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)
File "H5P.NDLATimeline-0.0/public/index.html" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)
File "H5P.NDLATimeline-0.0/public/old-index.html" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)
File "H5P.NDLATimeline-0.0/typings.d.ts" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.[Get help](https://h5p.org/documentation/troubleshooting#not-in-whitelist)

As explained in my original post, I have managed to add to .h5pignore all the needed files to be excluded _except for the dist/report.html file_. And I do not know how to do that...

**Comment by otacke** [comment]
@rezeau When you download H5P files from a page, the `.h5pignore` file should not be involved at all. H5P should simply copy the files from the directory that serves the files, so for Drupal from `/sites/default/files/h5p/libraries` or (if applicable) from `/sites/default/files/h5p/development`. If the latter contains files that are not supposed to be in an H5P file, there's your issue. That has nothing to do with the content types.

**Comment by rezeau** [comment]
@otacke I'll try once more to get you to understand my problem. Here's my detailed workflow:

1. Using Drupal 7 on my localhost I have enabled the Development folder at /sites/default/files/h5p/development. In that directory I have cloned my fork of H5P.NDLATimeline, installed npm and done npm run build (on the main, unmodified branch).
2. In my local drupal 7 site I create an H5P NDLA Timeline content, e.g. "Timeline Test 01" and save it.
3. I click on the H5P.NDLATimeline Reuse button and download that file to my computer's Download folder.
4. Then I go to one of the other local sites on my machine, either Drupal 9 OR Moodle OR Wordpress where I have previously installed H5P but _the NDLA Timeline library has not yet been installed_.
5. In my Edit interface I go to Add a new H5P Content and Under Select content type I click the Upload button.
6. I go to my Downloads folder and select the "Timeline Test 01" H5P file which I had previously downloaded there...
7. _I get the long error list of "not allowed" files as mentioned in my previous comments._
8. This is the expected way that H5P works for files which are not allowed and have not been put in the .h5pignore file.
9. Again I could solve this problem by adding those not-allowed files to the .h5pignore file except for the **dist/report.html** file, because for some reason .h5pignore does not report single files within a sub-folder.

**Comment by otacke** [comment]
@rezeau I fully understood you before, and my answer was according to what you described now in length.

H5P does not pack anything using the H5P CLI functions or .h5pignore when you download content, it simply copies the files from your libraries/development folder. If you have invalid files in there, they will end up in the H5P file which then itself will be invalid.

This has nothing to with any content type or misconfiguration.

**Pull request merged**
